site_verification:
  google: 
  baidu: code-zObFfpuvZ0

copyright: '<strong>本文作者：</strong> <a href="http:/github.com/qxdn">qxdn</a>'

google_site_id: UA-180828196-1

comment: disqus

disqus:
  shortname: qxdn-blog